//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _88DSL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DirectlineOrder
    {
        public string Status { get; set; }
        public string BBCode { get; set; }
        public string Sku { get; set; }
        public string Quantity { get; set; }
        public string BuyerName { get; set; }
        public int DirectlineOrderId { get; set; }
    }
}
