//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _88DSL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductInfo
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string ShippingCharges { get; set; }
        public string RegisteredFee { get; set; }
        public string ServiceFee { get; set; }
        public string ItemCode { get; set; }
    }
}
